# Generated by Django 6.1 on 2026-08-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(default='guest@company.com', max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('document_type', models.CharField(max_length=100)),
                ('confidence', models.FloatField(default=0.0)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('raw_json_response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
